# GitHub Action workflow to build and run Frida Fusion's tests
#

name: Test Build

on:
    push:
      branches: [ main ]
      paths-ignore:
        - .gitignore
        - README.md
        - LICENSE
        - TODO
        - frida_fusion/__meta__.py
        #- .github/workflows/build_and_test.yml

    pull_request:
      branches: [ main ]
      paths-ignore:
        - .gitignore
        - README.md
        - LICENSE
        - TODO
        - frida_fusion/__meta__.py
        - .github/workflows/build_and_test.yml

jobs:
  lint:
    name: Check syntaxs errors and warnings
    runs-on: ubuntu-latest
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    steps:
      - name: Checkout Frida Fusion
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8

      - name: Check syntax errors
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check PEP8 warnings
        run: |
          flake8 . --count --ignore=E1,E2,E3,E501,W291,W293 --exit-zero --max-complexity=65 --max-line-length=127 --statistics

  test:
    name: Run unit tests and build wheel
    needs: lint
    runs-on: ${{ matrix.os }}
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        experimental: [false]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - python-version: "3.12"
            experimental: true
            os: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout Frida Fusion
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'setuptools>=80.0.0'
          python -m pip install -r tests/requirements-test.txt

      - name: Remove requirements.txt
        if: "!contains(matrix.os, 'windows')"
        run: |
          rm -rf requirements.txt

      - name: Remove requirements.txt
        if: "contains(matrix.os, 'windows')"
        shell: cmd
        run: |
          del /F /Q requirements.txt

      - name: Install Frida Fusion
        run: |
          pip install .

      - name: Run unit tests
        run: |
          pytest -s tests/tests.py

      - name: Build artifact
        run: |
          python setup.py sdist

  publish:
    name: Publish on Test Environment
    needs: test
    runs-on: ubuntu-latest
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        experimental: [false]
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout Frida Fusion
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'setuptools>=80.0.0'
          python -m pip install -r tests/requirements-test.txt

      - name: Get latest tag
        id: latest_tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true

      - name: Change Package version
        run: |
          VER=$(echo "${{ steps.latest_tag.outputs.tag }}" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          if [ -z "$VER" ]; then
            VER="0.0.0"
          fi
          GITHASH=$(git rev-parse --short HEAD)
          meta=$(cat frida_fusion/__meta__.py | sed "s/__version__.*/__version__ = '"${VER}"'/" | sed "s/__build__.*/__build__ = 0x"${GITHASH}"/")
          echo "$meta" > frida_fusion/__meta__.py

      - name: Install Frida Fusion
        run: |
          pip install .

      - name: Build artifact
        run: |
          python setup.py sdist

      - name: Publish package in Test Environment
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.test_pypi_password }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true